# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff39e2b92004aa7c607e1dfc2af03ca6366003694375ca96d25d305d1a2b475117dc15eb5729d6af27a45ff6d6515b5c82818ad6ec9e08e98d8375c9c10c6bc4

test:
  secret_key_base: aa2371dc98f288d4030e49e785bb7e13a5bd73a356d920e794febeb9fd0956fe4f724d4dd60be91b4c2da79f9be7d25def540b3f7b25b035e928f9581aa033f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
